---
# tasks file for ansible-telegraf

- name: "Include variable definitions for {{ ansible_os_family }}"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Install on {{ ansible_os_family }}"
  include_tasks: "{{ ansible_os_family }}.yml"

- name: "Configure Telegraf"
  include_tasks: "configure_nix.yml"
  when:
  - ansible_os_family != "Windows"
