---
# handlers file for ansible-telegraf

- name: "Restart Telegraf"
  service:
    name: telegraf
    state: restarted
    enabled: yes
  when:
  - not telegraf_agent_docker
  - ansible_os_family in ["Debian", "FreeBSD", "Redhat", "Suse"]
  become: yes

- name: "Restart Telegraf"
  win_service:
    name: Telegraf
    start_mode: auto
    state: restarted
  when:
  - ansible_os_family == "Windows"

- name: "Restart Telegraf"
  shell: |
    brew services restart telegraf
  when:
  - ansible_os_family == "Darwin"

- name: "Restart Telegraf container"
  docker_container:
    name: "{{ telegraf_agent_docker_name }}"
    restart: True
  when: telegraf_agent_docker
